@startuml

entity programs {
  * program_id
  --
  movie_title
  detail
  length
  release_date
  views
}

entity program_list {
  * list_id
  --
  start_time
  end_time
  program_id(fk)
}

entity genres {
  * genre_id
  --
  genre_name
}

entity program_genre {
  * id
  --
  program_id
  genre_id
}

genres ||-r--|{ program_genre
programs ||--|{ program_genre
programs ||-u--|{ program_list



@enduml
